### ISSUE TITLE
keyboard-configurator backend forces static hidraw for hidapi crate

### ISSUE THREAD

**Issue by Conan-Kudo** [pop-os/keyboard-configurator#107]
While [reviewing this package for inclusion in Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2022176), I noticed that it forces the `linux-static-hidraw` feature instead of the `linux-shared-hidraw` feature from the `hidapi` crate. In Fedora, we'd prefer that C libraries be dynamically linked for these kinds of things.

Please consider switching the requested feature of the `hidapi` crate to `linux-shared-hidraw`.

**Comment by ids1024** [comment]
The `hidapi` crate defaults to static linking (but with libusb). But I don't see a problem with dynamic linking. Though I guess that's an extra runtime dependency for anyone trying to run `ectool` or `keyboard-configurator` from the git repos.

Too bad since Rust features are additive, there can't just be a `static-hidapi` or `dynamic-hidapi` cargo feature.
