### ISSUE TITLE
App Blurry on macOS Retina

### ISSUE THREAD

**Issue by jaxsnjohnson** [pop-os/keyboard-configurator#112]
In macOS (in image macOS 12) the app is blurry.  This is on  a MacBook Pro (Retina, 15-inch, Mid 2015).  I suspect it has something to do with retina & GTK.  Image bellow shows app, text and icons are blurry but other UI objects are sharp.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/79726860/144660261-554d7612-07c7-4fa1-9b02-24f079c00dcf.png">

**Comment by ids1024** [comment]
Okay, I've now discovered the magic command `sudo defaults write /Library/Preferences/com.apple.windowserver.plist DisplayResolutionEnabled -bool true` allows me to force the Mac Mini I have to display HiDPI display options, so I can finally test this.

I think it should just be a simple plist change, since Gtk 3 already supports DPI scaling.
