### ISSUE TITLE
Keyboard support for 840 G8

### ISSUE THREAD

**Issue by 25andros** [pop-os/keyboard-configurator#163]
# Intro

Hello devs;
purpose: Looking for support with this program for an HP Elitebook 840 G8, (identical to HP Dev, albeit Intel instead of AMD)

## Notes

-) popOS supports firmware natively for this laptop
-) same keyboard layout as HP Dev One
-)already download keyboard-configurator and it prompts "No keyboard dectected"

## Thoughts

- I believe there is a small configuration some where that would enable this for laptop and similar

**Comment by leviport** [comment]
This would be a very cool addition, but it's probably not feasible, unfortunately. What enables System76 laptops to have configurable keyboards with this keyboard configurator is the [System76 Open EC firmware](https://github.com/system76/ec) that most of our laptops have. Because the HP Dev One does not have Open EC, it also is not configurable with the keyboard-configurator. 

The firmware support you see for the 840 G8 and the Dev One is separate from System76 Open EC firmware. Those firmware updates are managed by [fwupd/LVFS](https://fwupd.org/), which Pop!\_OS has integrated, but the firmware being managed is still from HP, not System76, so the keyboard-configurator cannot interact with it and remap the keyboard.
